version: '3'

services:
  # app:
  #   build: .
  #   entrypoint: ./.docker/entrypoint.sh
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app
  #   depends_on:
  #     - db

  db:
    image: mongo:4.4.4
    container_name: db
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=nest

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      # - ME_CONFIG_MONGODB_SERVER=localhost
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - db
